CREATE TABLE clothes (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id INT NOT NULL,
    cloth_name VARCHAR NOT NULL,
    CONSTRAINT fk_users FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE wears (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    cloth_id INT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT fk_clothes FOREIGN KEY(cloth_id) REFERENCES clothes(id)
);